---
title: "Prepare figure 5 - figure supplements"
author: "Stefano Giulieri"
date: "08/03/2023"
output:
  html_document:
    toc: TRUE
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
setwd(stringr::str_c("~/Documents/Github/InToxSa", "/8-eLife_revision/Figure5_prepare"))
msg <- glue::glue("My directory is {getwd()}")
message(msg)
```

Here we prepare the figures supplements for figure 5


```{r message=FALSE}
library(tidyverse)
library(patchwork)
library(cols4all)
rm(list = ls())
```

# Set theme

```{r}
theme_set(theme_bw(base_size = 16))
theme_update( text = element_text(face = "bold"))
```

# GWAS on 28 genetic pairs

```{r}
(p1 <- readRDS("../Genetic_pairs/processed_data/GWAS/pyseer_output/all_variants/pyseer_output_toxicity_genes_all_plots.Rda")[[2]] +
   labs(title = "All variants"))
(
  p2 <- readRDS("../Genetic_pairs/processed_data/GWAS/pyseer_output/internal_variants/pyseer_output_toxicity_genes_all_plots.Rda") +
    labs(title = "Internal variants only") +
    scale_color_steps2(low = "blue", high = "red",
                     na.value = "grey90", name = "Effect size (transformed)",
                     breaks = seq(-1,1, .5), guide = "none")
  )
p1 + p2 +
  plot_annotation(tag_levels = "A") +
  plot_layout(guides = "collect")
```


```{r}
ggsave("figures/Figure5_figure_supplement1.pdf", width = 12)
```


# Pair with PI decreease *and* increase

```{r}
plot_list <- readRDS("../Genetic_pairs/processed_data/gene_convergence/PI_discordant_with_PI_increase/convergence_plots_diffPI.Rda")
wrap_plots(plot_list) +
  plot_annotation(tag_levels = "A")
```


```{r}
ggsave("figures/Figure5_figure_supplement2.pdf")
```

# Compare PI uptake

```{r}
plot_list <- readRDS("../Genetic_pairs/processed_data/gene_convergence/compare_PI_uptake_between_independent_pairs/comparison_plots.Rda")
(p1 <- plot_list[[1]] +
    labs(y = "Median\ndelta PI") +
    scale_fill_manual(values = c("red", "blue"), labels = c("pairs without\nmutations", "pairs with\nmutations"),
                      name = ""))
(p2 <- plot_list[[3]] +
    geom_hline(yintercept = 0) +
    labs(y = "Regression\ncoefficient beta") +
    scale_colour_brewer(palette = "YlGnBu") +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none"))
wrap_plots(p1, p2) +
  plot_annotation(tag_levels = "A") +
  plot_layout(guides = "collect")
```

```{r}
ggsave("figures/Figure5_figure_supplement3.pdf")
```


# Pairs with no / minimal PI change

```{r}
plot_list <- readRDS("../Genetic_pairs/processed_data/gene_convergence/PI_similar/convergence_plots_eqPI.Rda")
wrap_plots(plot_list) +
  plot_annotation(tag_levels = "A")

```

```{r}
ggsave("figures/Figure5_figure_supplement4.pdf")
```

