---
title: 'Parse results: plate 2 / exp190905'
author: "Stefano Giulieri"
date: "31/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse PI data

```{r}
PI_data <- parse_kinetics(file = "Raw_data/plate2/exp_190905/PI_kinetics/190830 HeLa 25000 Cell death rate dynamic.xlsx",
                          exp = "exp1900905",
                          duration = c(20,6),
                          n_skip = 14,
                          cell_number = 2.5e4,
                          plate = 2,
                          plot_data = T,
                          annotate = "minimal")
write_csv(PI_data,
          "Data_parsing/parsed_experiments/exp190905/PI_data_plate2_exp190905.csv")
```


# Parse growth data

```{r}
growth_data <- parse_growth(file = "Raw_data/plate2/exp_190905/Growth_curves/190904 plate 2 VANANZ growth for HeLa cells death real time.xlsx",
                            duration = c(15,45),
                            exp = "exp190905",
                            plate = 2,
                            normalised = T
)

# save growth data
growth_data %>%
  write_csv("Data_parsing/parsed_experiments/exp190905/growth_data_plate2_exp190905.csv")
```

