---
title: 'Parse results: plate GP-C1 / exp220328'
author: "Stefano Giulieri"
date: "31/03/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
message(msg)
```

```{r message=FALSE}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Set variable and directories

```{r}
plate <- "plateGP-C1"
experiment <- "exp220328"
raw_dir <- str_c("Raw_data", plate, experiment, "", sep = "/")
parse_dir <- str_c("Data_parsing/parsed_experiments/", plate, "_", experiment, "/")
cell_type <- "HeLa"
cell_number <- 1e5
```

# Parse PI data

```{r message=FALSE}
# parameters
PI_data <- parse_kinetics(file = list.files(str_c(raw_dir, "/PI_kinetics"), full.names = T, recursive = T),
                          exp = experiment,
                          cell_type = cell_type,
                          cell_number = cell_number,
                          interval = 5,
                          n_cycles = 280,
                          n_skip = 13,
                          wavelength = 535,
                          plate = str_remove(plate, "plate")) %>%
  annotate_wells(well_info = "plate_info/mutants_2022/well_info/well_info_plateGP-C1.csv", strain_group = "plate_info/mutants_2022/strain_info.csv") %>%
  left_join(read_csv("plate_info/mutants_2022/strain_info.csv")) %>%
  mutate(strain_group = if_else(sample_id == "BPH3370", "BPH3370-MUTANTS", strain_group))


# save PI data
PI_data %>%
  write_csv(str_c(parse_dir, "PI_data_", plate, "_", experiment, ".csv"))
```

# Quick check

```{r fig.height=9, fig.width=10}
my_title <- str_c("PI kinetics: ", plate, ", ", experiment)
my_subtitle <- str_c(cell_type, " infection, ", cell_number, " cells")

PI_data %>%
  filter(sample_id != "Complete lysis") %>% # mask complete lysis / need to scale because of very high values in these wells
  ggplot(aes(x = timepoint/60, y = f_signal)) +
  geom_point(colour = "#045a8d") +
  facet_wrap(strain_group~sample_id~strain_description) +
  labs(title = my_title,
       subtitle = my_subtitle) +
  theme_bw()
```

# Parse growth data

No growth data for this experiment.

```{r message=FALSE}
# # customise duration calculation
# growth_data <- parse_growth(file = list.files(str_c(raw_dir, "/Growth_curves"), full.names = T, recursive = T),
#                             duration = c(16, 50),
#                             interval = 10,
#                             n_skip = 12,
#                             well_cols = "merged",
#                             multiple_tranformations = c(1,1),
#                             exp = experiment,
#                             plate = str_remove(plate, "plate"),
#                             normalised = F,
#                             annotate = "none"
# ) %>%
#  annotate_wells(well_info = "plate_info/Nebraska_2021/well_info/well_info_plateGPV1.csv", annotation = "none") 
# 
# 
# # save growth data
# growth_data %>%
#   write_csv(str_c(parse_dir, "growth_data_", plate, "_", experiment, ".csv"))
```

# Quick check

```{r fig.height=9, fig.width=10}
# growth_data %>%
#   ggplot(aes(x = timepoint/60, y = OD)) +
#   geom_point(colour = "#045a8d") +
#   facet_wrap(strain_group~sample_id) +
#   theme_bw()
```


