---
title: 'Parse results: plate 2 / exp191107'
author: "Stefano Giulieri"
date: "04/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse PI data

```{r}
PI_data <- parse_kinetics(file = "Raw_data/plate2/exp_191107/PI_kinetics/191107 plate 2  HeLa 40000 real time cell death .xlsx",
                          exp = "exp191107",
                          n_cycles = 250,
                          wavelength = 535,
                          plate = 2,
                          annotate = "minimal")
# save PI data
write_csv(PI_data,
          "Data_parsing/parsed_experiments/exp191107/PI_data_plate2_exp191107.csv")
```


# Parse growth data

```{r}
growth_data <- parse_growth(file = "Raw_data/plate2/exp_191107/Growth_curves/191107 plate 2 gorwth ON in Clariostar plus for  HeLa 40000 real time cell death .xlsx",
                            duration = c(16,55),
                            interval = 5,
                            exp = "exp191107",
                            n_skip = 13,
                            well_cols = "merged",
                            plate = 2,
                            normalised = T
)
# save growth data
growth_data %>%
  write_csv("Data_parsing/parsed_experiments/exp191107/growth_data_plate2_exp191107.csv")
```
