---
title: "Create mutations minimaps for convergent genes"
author: "Stefano Giulieri"
date: '24/06/2022'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(stringr::str_c(here::here(), "/InToxSa_paper/Genetic_pairs"))
msg <- glue::glue("My directory is {getwd()}")
message(msg)
```

Here we create mutations minimaps for convergent genes (or for all mutated genes). These maps will show the positions of mutations, the amino acid at residue and the amino acid sequence change

```{r}
library(tidyverse)
library(ggrepel)

rm(list = ls())
```

# Raw data

Mutations

```{r}
df_mutations <- df_mutations <- readRDS("../../../VANANZ_phenotypes_local/Genetic_pairs_analysis_Oct_2020/processed_data/convergence/PI/df_PI_convergent_genes.Rda")

df_mutations <- readRDS("../../../VANANZ_phenotypes_local/InToxSa_paper/Genetic_pairs/processed_data/variants_combined_annotation/df_changes_multi_annotated.Rda")
```

Pairs data

```{r}
pairs_data <- readRDS("processed_data/PI_pairs_data/pairs_description_with_phylo_dataframe.Rda") %>%
  filter(PI_pair)
```

We keep only mutations included in pairs

```{r}
df_mutations <- df_mutations %>%
  semi_join(pairs_data, by = "pair_id") %>%
  distinct()
```

# Try agrA

```{r}
df_agrA <- df_mutations %>%
  filter(pan_gene_symbol == "agrA") %>%
  select(pair_id, AA_POS, MUTATION_SHORT, EFFTYPE_SHORT) %>%
  arrange(AA_POS) %>%
  distinct()
```

Plot mutations

```{r}
colors <- RColorBrewer::brewer.pal(n = 6, name = "PuOr")
colors_genes <- colors[1:3]
names(colors_genes) <- rev(c( "synonymous", "non-synonymous", "truncating"))

colors_genes

df_plot <- df_agrA %>%
  mutate(pair_id = fct_reorder(pair_id, AA_POS)) %>%
  group_by(pair_id) %>%
  mutate(pair_number = cur_group_id()) 

df_plot %>%
  ggplot(aes(x = AA_POS, label = label, y = .5)) +
  geom_segment(aes(x = AA_POS, xend = AA_POS, y = 0, yend = .5), colour = "red", size = 1) +
  geom_label_repel(min.segment.length = 0, direction = "x", position = position_nudge_repel(x = 0, y = 1)) +
  scale_y_continuous(limits = c(NA, 3)) +
  theme_bw()

df_plot %>%
  ggplot(aes(x = AA_POS, label = label, y = .5,  fill = EFFTYPE_SHORT)) +
  geom_segment(aes(x = AA_POS, xend = AA_POS, y = 0, yend = .5),  size = 1, colour = "black") +
  geom_label_repel(colour = "black", min.segment.length = 0, segment.size = .5, segment.linetype = 2,  position = position_nudge_repel(x = 0, y = df_plot$pair_number)) +
  scale_y_continuous(limits = c(0, 10), expand = c(0,0), breaks =  NULL) +
  scale_fill_manual(values = colors_genes, guide = "none") +
  labs(x = "Amino acid position", y = "Genetic pair", title = "agrA") +
  theme_bw(base_size = 16)+
  theme(plot.title = element_text(hjust = .5),
        panel.grid = element_blank(),
        text = element_text(face = "bold"))
```

Now for all 3 genes

```{r}
df_genes <- df_mutations %>%
  filter(pan_gene_symbol %in% c("agrA", "agrC", "ausA")) %>%
  select(pair_id, pan_gene_symbol, AA_POS, MUTATION_SHORT, EFFTYPE_SHORT) %>%
  arrange(AA_POS) %>%
  distinct()
```

Plot multipanel

```{r}
df_plot <- df_genes %>%
  ungroup() %>%
  arrange(pan_gene_symbol, AA_POS) %>%
  mutate(row = row_number()) %>%
  group_by(pair_id) %>%
  mutate(pair_number = min(row)) 

# df_plot %>%
#   ggplot(aes(x = AA_POS, label = label, y = .5)) +
#   geom_segment(aes(x = AA_POS, xend = AA_POS, y = 0, yend = .5), colour = "red", size = 1) +
#   geom_label_repel(min.segment.length = 0, direction = "x", position = position_nudge_repel(x = 0, y = 1)) +
#   scale_y_continuous(limits = c(NA, 3)) +
#   theme_bw()

p1 <- df_plot %>%
  ggplot(aes(x = AA_POS, label = MUTATION_SHORT, y = .5,  fill = EFFTYPE_SHORT)) +
  geom_segment(aes(x = AA_POS, xend = AA_POS, y = 0, yend = .5),  size = 1, colour = "black") +
  geom_label_repel(colour = "black", min.segment.length = 0, segment.size = .5, segment.linetype = 2,  position = position_nudge_repel(x = 0, y = df_plot$pair_number), direction = "x") +
  scale_y_continuous(limits = c(0, 15), expand = c(0,0), breaks =  NULL) +
 scale_fill_manual(values = colors_genes, name = "Mutation effect", guide = guide_legend(override.aes = aes(label = ""))) +
  facet_wrap(~pan_gene_symbol, scales = "free_x") +
  labs(x = "Amino acid position", y = "Genetic pair") +
  theme_bw(base_size = 16)+
  theme(plot.title = element_text(hjust = .5),
        panel.grid = element_blank(),
        text = element_text(face = "bold"))
p1

p2 <- df_plot %>%
  ggplot(aes(x = AA_POS, label = MUTATION_SHORT, y = .5,  fill = EFFTYPE_SHORT)) +
  geom_segment(aes(x = AA_POS, xend = AA_POS, y = 0, yend = .5),  size = 1, colour = "black") +
  geom_label_repel(colour = "black", min.segment.length = 0, segment.size = .5, segment.linetype = 2,  position = position_nudge_repel(x = 0, y = 1), direction = "x") +
  scale_y_continuous(limits = c(0, 4), expand = c(0,0), breaks =  NULL) +
  scale_fill_manual(values = colors_genes, name = "Mutation effect", guide = guide_legend(override.aes = aes(label = ""))) +
  facet_wrap(~pan_gene_symbol, scales = "free_x") +
  labs(x = "Amino acid position", y = "") +
  theme_bw(base_size = 16)+
  theme(plot.title = element_text(hjust = .5),
        panel.grid = element_blank(),
        text = element_text(face = "bold"))
p2
```

# Save processed data

```{r}
list(p1, p2) %>%
  saveRDS("processed_data/gene_convergence/mutations_minimaps.Rda")
```

