---
title: "Prepare figure 4"
author: "Stefano Giulieri"
date: "24/06/2022"
output:
  html_document:
    toc: TRUE
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
setwd(stringr::str_c("~/Documents/Github/InToxSa", "/6-InToxSa_paper/Figure4_prepare"))
msg <- glue::glue("My directory is {getwd()}")
message(msg)
```

Here we prepare the figure summarising mutagenesis experiments.

Design of the figure: 

Upper half: mutations miniplots for 3 genes with confirmed PAM: agrA, agrC and ausA.

Lower half: PI uptake change and Operetta metrics for reconstructed mutants in BPH3370 wt.

```{r message=FALSE}
library(tidyverse)
library(patchwork)
library(cols4all)
rm(list = ls())
```

# Import mutation minimaps

```{r}
plot_list <- readRDS("../Genetic_pairs/processed_data/gene_convergence/mutations_minimaps.Rda")
p1 <- plot_list[[1]] 
p1
```

# Import PI phenotype of the mutants

```{r}
p2 <- readRDS("../Mutagenesis/processed_data/mutagenesis_pi_auc_plots.Rda")
p2
```

# Compose figure

```{r}
p3 <- p1 / p2  +
  plot_annotation(tag_levels = "A")
p3



# ggsave("figures/Figure4.pdf", width = 14, height = 10)
```



