---
title: 'Parse results: plate P1 / exp200219'
author: "Stefano Giulieri"
date: "02/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse data

```{r}
# parameters
PI_data <- parse_kinetics(file = "Raw_data/plateP1/exp200219/PI_kinetics/200219 Plate P1 n1 HeLa 40000 cell death assay.xlsx",
                          exp = "exp200219",
                          n_cycles = 237,
                          plate = "P1",
                          n_skip = 14,
                          plot_data = T,
                          annotate = "none") %>%
  annotate_wells(well_info = "plate_info/well_info_plates_P1_P2.csv")
# save PI data
PI_data %>%
  write_csv("Data_parsing/parsed_experiments/exp200219/PI_data_plateP1_exp200219.csv")
```

Note the warning `the number of parsed well is not 96`. This is because the outer wells are not used in plate P1.

# Parse growth data

```{r}
growth_data <- parse_growth(file = "Raw_data/plateP1/exp200219/Growth_curves/Plate P1 n1 ON growth.xlsx",
                            duration = c(15,50),
                            interval = 10,
                            exp = "exp200219",
                            plate = "P1",
                            normalised = F,
                            annotate = "none"
) %>%
  annotate_wells(well_info = "plate_info/well_info_plates_P1_P2.csv")

# save growth data
growth_data %>%
  write_csv("Data_parsing/parsed_experiments/exp200219/growth_data_plateP1_exp200219.csv")
```
