---
title: 'Parse results: plate 2 / exp190831'
author: "Stefano Giulieri"
date: "02/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse PI data

```{r}
PI_data <- parse_kinetics(file = "Raw_data/plate2/exp_190831/PI_kinetics/190831 LD PI Assay VANANZ 24 hours.xlsx",
                          exp = "exp190831",
                          duration = c(22,42),
                          n_skip = 14,
                          cell_number = 4e4,
                          plate = 2,
                          plot_data = T,
                          annotate = "minimal")
write_csv(PI_data,
          "Data_parsing/parsed_experiments/exp190831/PI_data_plate2_exp190831.csv")

```


# Parse growth data

```{r}
growth_data <- parse_growth(file = "Raw_data/plate2/exp_190831/Growth_curves/190829 plate 2 VANANZ OD600 Growth ON for real time PI cell death.xlsx",
                            duration = c(16,0),
                            exp = "exp190831",
                            plate = 2
)
# plot the data
growth_data %>%
  ggplot(aes(x = timepoint/60, y = OD)) +
  stat_summary(geom = 'ribbon', fun.data = 'mean_sdl', fun.args = list(mult = 1), fill = "#045a8d", alpha = 0.2) + 
      stat_summary(geom = "point", fun.y = "mean", color = "#045a8d", size = 1) +
      facet_wrap(strain_group ~ sample_id, ncol = 8) +
      labs(x = "Time (hour)",
           y = "OD") +
      theme_bw()
# save growth data
growth_data %>%
  write_csv("Data_parsing/parsed_experiments/exp190831/growth_data_plate2_exp190831.csv")
```

