---
title: 'VANANZ dynamic cytotoxicity: parsing growth data'
author: "Stefano Giulieri"
date: "07/10/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(readxl)

rm(list = ls())
```

### Growth kinetics

```{r}
source("../../Functions/parse_results.R")
```

## exp 190831

```{r}
# arguments for parsing
file <- "../Raw_data/plate2/exp_190831/Growth_curves/190829 plate 2 VANANZ OD600 Growth ON for real time PI cell death.xlsx"
duration <- c(16, 0)
exp <- "exp190831"
plate <- 2

# parse data
data <- parse_growth(file, duration = duration, exp = exp, plate = plate)
data

growth_data <- list()
growth_data[[1]] <- data
```

## exp 190905

```{r}
# arguments for parsing
file <- "Preliminary_analysis/Raw_data/exp_190905/Growth_curves/190904 plate 2 VANANZ growth for HeLa cells death real time.xlsx"
duration <- c(15, 45)
exp <- "190905"
plate <- 2

# parse data
data <- parse_OD(file, duration = duration, normalised = TRUE, exp = exp, plate = plate)
data

OD_data[[2]] <- data
```

Data for experiment 190905 are normalised based on blanks. We need to get the raw data or alternatively apply normalisation to all.

## exp 190909

```{r}
# arguments for parsing
file <- "Preliminary_analysis/Raw_data/exp_190909/Growth_curves/190909.plate.2.VANANZ.ON.growth.for.HeLa.cells.death.real.time.number.3.xlsx"
duration <- c(17, 0)
exp <- "190909"
plate <- 2

# parse data
data <- parse_OD(file, duration = duration, normalised = TRUE, exp = exp, plate = plate)
data

OD_data[[3]] <- data
```

Data are normalised

## merge dataframes

```{r}
OD_data <- bind_rows(OD_data)
```

### Inocula OD

## exp 190831

```{r}
source("Functions/parse_results.R")
# arguments for parsing
file <- "Preliminary_analysis/Raw_data/exp_190831/Inocula_OD/190829 plate 2 VANANZ OD600 blank corrected pbs 1 in 10 list.xlsx"
exp <- "310831"
plate <- 2

# parse results
data <- parse_inocula_OD(file, normalised = TRUE, exp = exp, plate = plate)
data

inocula_OD_data <- list()
inocula_OD_data[[1]] <- data
```

## exp 190905

```{r}
# arguments for parsing
file <- "Preliminary_analysis/Raw_data/exp_190905/Inocula_OD/190904 plate 2 VANANZ growth for HeLa cells death real time diluted 1 in 10 in PBS.xlsx"
exp <- "310905"
plate <- 2

# parse results
data <- parse_inocula_OD(file, normalised = TRUE, exp = exp, plate = plate)
data

inocula_OD_data[[2]] <- data
```

## exp 190909

```{r}
# arguments for parsing
file <- "Preliminary_analysis/Raw_data/exp_190909/Inocula_OD/190909 plate 2 VANANZ dilution 1 in  10 for HeLa cells death real time number 3.xlsx"
exp <- "310909"
plate <- 2

# parse results
data <- parse_inocula_OD(file, normalised = TRUE, exp = exp, plate = plate)
data

inocula_OD_data[[3]] <- data
```

## merge dataframes

```{r}
inocula_OD_data <- bind_rows(inocula_OD_data)
```

