---
title: "Compare JE2 across plates"
author: "Stefano Giulieri"
date: "09/12/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(magrittr)

rm(list = ls())
```

# Import data

```{r message=FALSE}
# setwd("Data_analysis")
file <- "../Data_parsing/dataframes/all_PI_kinetics_well_info.csv"
df_kinetics <- read_csv(file)
df_kinetics

JE2_dat <- df_kinetics %>%
  filter(sample_id == "JE2")
JE2_dat
```

# Plot JE2 curves

```{r message=FALSE}
title <- "JE2 dynamic toxicity across experiments"
df <- JE2_dat %>%
  mutate(experiment = str_c("Plate ", plate, " - ", experiment, "\n(", cell_number, " cells)")) %>%
  filter(wave_length == "WL535" & cell_number == 4e4)
df %>%
  ggplot(aes(x = timepoint, y = f_signal)) +
  geom_point(size = .5, color = "red") +
  growthcurve::stat_growthcurve(model = "spline", color = "black") +
  facet_wrap(~experiment) +
  labs(title = title,
       x = "Time (min)",
       y = "Fluorescence intensity") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

# Compare with inoculum OD data

```{r message=FALSE}
file <- "../Data_parsing/dataframes/all_inoculum_OD_well_info.csv"
inocula_data <- read_csv(file)

JE2_inocula_data <- inocula_data %>%
  filter(sample_id == "JE2") %>%
  filter(inoculum_OD_blank_normalised) %>%
  select(well, inoculum_OD, sample_id, experiment)
# merge
df <- JE2_dat %>%
  left_join(JE2_inocula_data, by = c("well", "sample_id", "experiment"))
df
```

```{r}
df %>%
  mutate(experiment = str_c("Plate ", plate, " - ", experiment, "\n", "inoculum OD: ", inoculum_OD)) %>% 
  filter(wave_length == "WL535" & cell_number == 4e4) %>%
  mutate(experiment = fct_reorder(experiment, inoculum_OD)) %>%
  ggplot(aes(x = timepoint, y = f_signal)) +
  geom_point(size = .5, color = "red") +
  growthcurve::stat_growthcurve(model = "spline", color = "black") +
  facet_wrap(~experiment) +
  labs(title = title,
       x = "Time (min)",
       y = "Fluorescence intensity") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

# Normalise plates using JE2

To normalise we will use following formula:
f_signal - mean(f_signal[JE2])/sd(f_signal[JE2])

```{r message=FALSE}
file <- "../Data_parsing/dataframes/all_PI_kinetics_well_info.csv"
kinetics_data <- read_csv(file) %>%
  filter(cell_number == 4e4 & wave_length == "WL535")

# plate 4 only
plate4_data <- kinetics_data %>%
  filter(plate == 4)
```

```{r}
# normalise plate 4
plate4_norm <- plate4_data %>%
  group_by(experiment) %>%
  mutate(f_signal_norm = (f_signal - mean(f_signal[which(sample_id == "JE2")]))/
           sd(f_signal[which(sample_id == "JE2")])) %>%
  ungroup()
title <- "Plate 4: standardised using JE2"
plate4_norm %>%
    ggplot(aes(x = timepoint, y = f_signal_norm)) +
    geom_point(size = .5, color = "red") +
    growthcurve::stat_growthcurve(model = "spline", color = "black") +
    facet_grid(experiment ~ sample_id, scales = "free") +
    labs(title = title,
         x = "Time (min)",
         y = "Fluorescence intensity") +
    theme_bw() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
# compare to raw data
source("../Functions/plot_results.R")
plot_toxicity(df = plate4_norm, plate_number = 4)
```

