---
title: "Plate 2 pretty plotting"
author: "Stefano Giulieri"
date: "16/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Pretty plot of plate 2 for meeting on 17 december 2019.

```{r}
rm(list = ls())

library(tidyverse)
library(magrittr)

# directory stuff
dir <- here::here("Data_analysis")
setwd(dir)

# scripts
source("../Functions/plot_results.R")
```

## The data

```{r}
file <- "../Data_parsing/dataframes/all_PI_kinetics_well_info.csv"
kinetics_data <- read_csv(file) %>%
  filter(plate == 2 & cell_number == 4e4)
# add sample group
file <- "../plate_info/sample_list_plate.csv"
group_info <- read_csv(file) %>%
  select(-plate, strain_group = studyid)
df_plate2 <- kinetics_data %>%
  left_join(group_info,
            by = c("sample_id" = "mdu_id")) %>%
  replace_na(list(strain_group = "Controls")) %>%
  mutate(timepoint = timepoint/60)
```

## First plot

```{r}
# Number of experiments
exps <- unique(df_plate2$experiment)

#exp190831
exp <- exps[1]
df <- df_plate2 %>%
  filter(experiment == exp)

# extract total cell death and natural cell death valuee from fitted spline of Total LDH and non infected, respectively


df_plate2 %>%
  growthcurve::fit_growth(time = timepoint, data = f_signal) -> t
t$fit



growthcurve::gggrowthcurve(t)
growthcurve::tidy.growthcurve(t) -> a
broom::(t)
t$type
t$model
t$fit
t$parameters
t$data

df %>%
  filter(wave_length == "WL535") %>%
  filter(sample_id == "Complete lysis") %>%
  #group_by(plate) %>%
  ggplot(aes(x = timepoint, y = f_signal)) +
  growthcurve::stat_growthcurve(aes(outfit=fit<<-..y..), model = "spline", color = "black")

total_cell_death <- max(fit)

df %>%
  filter(wave_length == "WL535") %>%
  filter(sample_id == "Non infected") %>%
  ggplot(aes(x = timepoint, y = f_signal)) +
  growthcurve::stat_growthcurve(aes(outfit=fit<<-..y..), model = "spline", color = "black")

natural_cell_death <- max(fit)

# plot
title <- str_c("Plate 2 - ", exp)
plot_toxicity_facet_wrap(df = df, plate_number = 2, n_row = 2) +
  # geom_hline(yintercept = total_cell_death, linetype = "dashed") +
  geom_hline(yintercept = natural_cell_death, linetype = "dashed") +
  ggtitle(title) +
  labs(x = "Time (hours)")

# create figures directory
dir <- "figures"
if (!dir.exists(dir)) dir.create(dir)

# save plot
file <- str_c("figures/plate2_", exp, ".pdf")
ggsave(file, width = 15, height = 8.5)
```

```{r}
#exp191107
exp <- exps[2]
df <- df_plate2 %>%
  filter(experiment == exp)


df %>%
  filter(wave_length == "WL535") %>%
  filter(sample_id == "Complete lysis") %>%
  #group_by(plate) %>%
  ggplot(aes(x = timepoint, y = f_signal)) +
  growthcurve::stat_growthcurve(aes(outfit=fit<<-..y..), model = "spline", color = "black")

total_cell_death <- max(fit)

df %>%
  filter(wave_length == "WL535") %>%
  filter(sample_id == "Non infected") %>%
  ggplot(aes(x = timepoint, y = f_signal)) +
  growthcurve::stat_growthcurve(aes(outfit=fit<<-..y..), model = "spline", color = "black")

natural_cell_death <- max(fit)

# plot
title <- str_c("Plate 2 - ", exp)
plot_toxicity_facet_wrap(df = df, plate_number = 2, n_row = 2) +
  geom_hline(yintercept = total_cell_death, linetype = "dashed") +
  geom_hline(yintercept = natural_cell_death, linetype = "dashed") +
  ggtitle(title) +
  labs(x = "Time (hours)")

# save plot
file <- str_c("figures/plate2_", exp, ".pdf")
ggsave(file, width = 15, height = 8.5)
```

## VAN-024 plot

```{r}
group <- "VAN-024"
df <- df_plate2 %>%
  filter(strain_group == group | strain_group == "Controls")

# try one experiment
i <- exps[1]

# get dataframe
df_filt <- df[df$experiment == i,]

# get total and natural cell death
total_cell_death
print(str_c("Total cell death is ", total_cell_death))

natural_cell_death 
print(str_c("Natural cell death is ", natural_cell_death))

# actual plot
title <- str_c("Plate 2 - ", exp, " - ", group)
p <- plot_toxicity_facet_wrap(df = df_filt, plate_number = 2, n_row = 1) +
  geom_hline(yintercept = total_cell_death, linetype = "dashed") +
  geom_hline(yintercept = natural_cell_death, linetype = "dashed") +
  ggtitle(title) +
  labs(x = "Time (hours)")

















# # plot 
# plot_list <- list()
# for (i in exps){
#   
#   # get dataframe
#   df_filt <- df[df$experiment == i,]
#   
#   # get total and natural cell death
#   # create growthcurve object
#   t <- df_filt %>%
#     growthcurve::fit_growth(time = timepoint, data = f_signal) 
#   t$fit
#   
#   
#   total_cell_death <- max(fit)
#   print(str_c("Total cell death is ", total_cell_death))
# 
#   
#   
#   natural_cell_death <- max(fit)
#   print(str_c("Natural cell death is ", natural_cell_death))
#   
#   # actual plot
#   title <- str_c("Plate 2 - ", exp, " - ", group)
#   p <- plot_toxicity_facet_wrap(df = df_filt, plate_number = 2, n_row = 1) +
#     geom_hline(yintercept = total_cell_death, linetype = "dashed") +
#     geom_hline(yintercept = natural_cell_death, linetype = "dashed") +
#     ggtitle(title) +
#     labs(x = "Time (hours)")
#   
#   # add to list
#   plot_list[[i]] <- p
#   
# }
# 
# # install.packages("patchwork")
# library(patchwork)
# wrap_plots(plot_list, nrow = 2)
# 
# 
# ggsave("figures/VAN-024.pdf", width = 12, height = 8)
```

