---
title: "Summarise all VANANZ analyses performed so far"
author: "Stefano Giulieri"
date: "02/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

This script summarises all VANANZ analyses performed so far: plates 1-6, P1-P2 (M1 to be added pending preliminary analysis).

```{r}
library(tidyverse)
library(magrittr)
# rm(list = ls())
source("Functions/all_functions.R")
```

# Upload parsed data

```{r message=FALSE}
PI_kinetics_data_all <- read_csv("Data_parsing/dataframes/partial_datasets/all_PI_kinetics_well_info.csv") %>%
  mutate(plate = as.character(plate)) %>%
  full_join(read_csv("Data_parsing/dataframes/partial_datasets/plateP1_PI_kinetics_well_info.csv")) %>%
  full_join(read_csv("Data_parsing/dataframes/partial_datasets/plateP2_PI_kinetics_well_info.csv"))
```

Perform a few checks to confirm that the merging worked

```{r}
# List of plates
PI_kinetics_data_all %>% .$plate %>% unique()
# Number of isolates
PI_kinetics_data_all %>% .$sample_id %>% unique()
# save dataset
PI_kinetics_data_all %>%
  mutate(plate = as.character(plate)) %>%
  arrange(desc(plate)) %>%
  write_csv("Data_parsing/dataframes/concatenated_datasets/PI_kinetics_data.csv")
```

# Filter outliers: JE2

```{r fig.height=20, fig.width=10}
df_cell_death <- PI_kinetics_data_all
df_JE2  <- JE2_POMS_standardisation(df = df_cell_death) %>%
  filter(sample_id == "JE2")
plot_cell_death(df = df_JE2, standardized = T, combine_experiments = "all", annotate = T)
```

We remove 2 JE2 outliers 

```{r}
JE2.outliers <- c("exp191121_4_B06", "exp191121_4_D06")
df_cell_death_noJE2.outliers <- df_cell_death %>%
  filter(!well_id %in% JE2.outliers)
df_cell_death_noJE2.outliers_std <- JE2_POMS_standardisation(df_cell_death_noJE2.outliers,
                                                             plot = F)
```

# Remove other outliers

```{r}
outliers <- read_csv("Data_analysis/outliers/PI_kinetics_VANANZ_outliers.csv") %>%
  .$well_id
df_cell_death_clean_std <- df_cell_death_noJE2.outliers_std %>%
  filter(!well_id %in% outliers)
# save 
df_cell_death_clean_std %>%
  write_csv("Data_analysis/dataframes/df_cell_death_clean_std_manual.csv")
```

# Fit 

```{r}
df_cell_death_clean_std_fit <- fit_smooth_spline(df_cell_death_clean_std)
```

# Add metadata

```{r}
df_cell_death_clean_std_fit_metadata <- df_cell_death_clean_std_fit %>%
  left_join(read_csv("plate_info/strain_metadata.csv"))
```


# Extract parameters

```{r}
cell_death_parameters <- get_parameters(df = df_cell_death_clean_std_fit_metadata)
# save parameters
cell_death_parameters %>%
  write_csv("Data_analysis/dataframes/cell_death_parameters.csv")
```

# Repeat analyse of aggregate parameters

```{r}
# Mortality using AUC
df_means <- cell_death_parameters %>%
  # filter(plate != 4) %>%
  # remove same patient isolates
  filter(intrahost_index == 1 | is.na(intrahost_index)) %>%
            filter(!sample_id %in% c("Complete lysis", "Non infected")) %>%
            mutate(group = if_else(strain_group == "CONTROL", 
                                   sample_id,
                                   mortality)) %>%
  group_by(sample_id, group, plate, ST) %>%
  summarise(AUC = mean(AUC),
            max_death = mean(max_death))
df_means %>% 
  ggplot(aes(x = group, y = AUC)) +
  geom_boxplot() +
  geom_jitter() +
  geom_hline(yintercept = df_cell_death_parameters %>%
               filter(sample_id == "JE2") %>% .$AUC %>% mean()) +
  coord_flip() +
  theme_bw() +
    theme(legend.position = "none") 

# Stats test
df_stat <- cell_death_parameters %>%
  drop_na(mortality)
wilcox.test(df_stat$AUC[which(df_stat$mortality == "Died")], 
            df_stat$AUC[which(df_stat$mortality == "Survived")])

# With means
df_stat_means <- df_stat %>%
  group_by(sample_id, mortality) %>%
  summarise(AUC = mean(AUC),
            max_death = mean(max_death))
wilcox.test(df_stat_means$AUC[which(df_stat_means$mortality == "Died")], 
            df_stat_means$AUC[which(df_stat_means$mortality == "Survived")])
```

```{r}
# Using max death
df %>% 
  ggplot(aes(x = group, y = max_death)) +
  geom_boxplot() +
  geom_jitter() +
  geom_hline(yintercept = df_cell_death_parameters %>%
               filter(sample_id == "JE2") %>% .$max_death %>% mean()) +
  coord_flip() +
  theme_bw() +
    theme(legend.position = "none") 
wilcox.test(df_stat_means$max_death[which(df_stat_means$mortality == "Died")], 
            df_stat_means$max_death[which(df_stat_means$mortality == "Survived")])

```

