---
title: 'Parse results: plate 5 / exp200320'
author: "Stefano Giulieri"
date: "25/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse growth data

```{r}
growth_data <- parse_growth(file = "Raw_data/plate5/exp_200320/Growth_curves/200320  Plate Vananz 5 n3 ON growth.xlsx",
                            duration = c(23,40),
                            interval = 10,
                            exp = "exp200320",
                            plate = "5",
                            normalised = T,
                            annotate = "minimal"
) 


# save growth data
growth_data %>%
  write_csv("Data_parsing/parsed_experiments/exp200320/growth_data_plate5_exp200320.csv")
```