---
title: 'Parse results: plate 3 / exp190923'
author: "Stefano Giulieri"
date: "04/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse PI data

```{r}
PI_data <- parse_kinetics(file = "Raw_data/plate3/exp_190923/PI_kinetics/190923 plate VANANZ 3 HeLa real time cell death n5.xlsx",
                          exp = "exp190923",
                          n_cycles = 224,
                          plate = 3,
                          cell_number = 2e4,
                          wavelength = 535)
# save data
write_csv(PI_data,
          "Data_parsing/parsed_experiments/exp190923/PI_data_plate3_exp190923.csv")
```


# Parse growth data

No growth curves available for this experiment.