---
title: "Generate genetic pairs table"
author: "Stefano Giulieri"
date: "27/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(paste0(here::here(), "/6-InToxSa_paper/Generate_datasets"))
getwd()
```

Here we prepare supp table 4 with genetic pairs data: first sheet phenotype, second sheet mutations

```{r}
library(tidyverse)
library(writexl)
rm(list = ls())
```

# Import phentype

```{r}
pheno <- readRDS("../Genetic_pairs/processed_data/PI_pairs_data/pairs_description_dataframe.Rda") %>%
  filter(PI_pair) %>%
  select(pair_id, iso1, iso2, dist_denovo, delta_auc, pval, dist_new, dist_mash)

supp_table4_prepare <- list(phenotype = pheno)
```

# Mutations

```{r}
mutations <- readRDS("../Genetic_pairs/processed_data/gene_convergence/df_changes_multi_annot_for_gene_converg.Rda") 
mutations <- mutations %>%
  ungroup() %>%
  select(pair_id, iso1, iso2, CHROM, POS, TYPE, EFFTYPE, REF, ALT, NUCLEOTIDE_CHANGE, MUTATION_SHORT, LOCUS_TAG, GENE, PRODUCT, cdhit_group, cdhit_size, cdhit_iden, cdhit_cov, cdhit_rep_id, cdhit_seq, neb_locus_tag, unique_gene_symbol = neb_gene_symbol, neb_product, neb_mutant_id, neb_operon) %>%
  distinct()

supp_table4_prepare$mutations <- mutations
```

# List of variables (pyseer output only)

```{r}
variables <- unique(c(colnames(pheno), 
                             colnames(mutations)))
variables <- tibble(variable = variables,
                           comment = NA_character_)

supp_table4_prepare$`variables` <- variables
```

# Export as supplementary table

```{r}
supp_table4_prepare %>%
  write_xlsx("processed_data/supp_table_4/supp_table_4.xlsx")
```