---
title: "Generate isolates table"
author: "Stefano Giulieri"
date: "27/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(paste0(here::here(), "/InToxSa_paper/Generate_datasets"))
getwd()
```

Here we prepare table 1 and supp table 1 with isolates information

```{r}
library(tidyverse)
library(writexl)
rm(list = ls())
```

# Import current isolates table

```{r}
data <- readRDS("../Phylogeny/processed_data/curated_metadata_tree.Rda")
```

Add some layers of information

Episode id, mortality

```{r}
clinical_data <- read_csv("../../plate_info/strain_metadata.csv") %>%
  transmute(sample_id, strain_group, mortality, baseline_isolate = if_else(intrahost_index == 1, "Yes", "No", missing = "Yes"))
```

Duration of bacteraemia, severity

```{r}
f <- "~/OneDrive - The University of Melbourne/R/Clinical_outcomes_prediction/VANANZ/Clean_clinical_data/raw_data/df_clinical.csv"
file.copy(f, "raw_data/additional_clinical_data.csv")
clinical_data2 <- read_csv("raw_data/additional_clinical_data.csv") %>%
  select(sample_id = mdu_id, sab_duration = durationofsab, severity_score = pitt)
```

New layered dataset

```{r}
df_clinical <- data %>%
  left_join(clinical_data) %>%
  left_join(clinical_data2) %>%
  mutate(genetic_pair = !is.na(iso_class),
         mortality = factor(mortality))
```

# Generate table 1

N episodes

```{r}
df_clinical %>%
   mutate(n = n_distinct(strain_group)) %>%
  group_by(genetic_pair, n) %>%
  summarise(n_episode = n_distinct(strain_group)) 
```

Table 1 all isolates

```{r}
# CC
cc <- df_clinical %>%
  count(CC, sort = T) %>%
  mutate(frac = scales::percent(n/sum(n)))
# mec
mec <- df_clinical %>%
  count(mecA, sort = T) %>%
  mutate(frac = scales::percent(n/sum(n)))
mec
```

# Export as supplementary table

```{r}
supp_table1_prepare <- df_clinical %>%
  select(sample_id, episode_id = strain_group, baseline_isolate, iso_class, ST, CC, mecA)

list(supp_table1_prepare, as_tibble(colnames(supp_table1_prepare))) %>%
  set_names(c("dataset", "variables")) %>%
  write_xlsx("processed_data/supp_table_1/supp_table_1.xlsx")
```


