output_dir: sim1_size300
num_species: 300
genome_length: 1000000
mutation_rate: 0.06
recomb_rate: 0.01
maf: 0.01
num_var: 150000
random_seed: 1487
phen_type: quant
num_causal_var: 16
causal_maf_min: 0.1
causal_maf_max: 0.4
causal_ld_max: 0.6
effect_size_odr: '2,3,4,7,10,11,15,20'
phen_replication: 10
heritability: 0.5
disease_prevalence: 0.5
case: 50
control: 50
simvis_dpi: 100
plot_ld: yes
snp_limit: 1000
ld_maf: 0.1
cores: 8
latency_wait: 3
