---
title: "Keep track of experiments and raw data parsing"
author: "Stefano Giulieri"
date: "03/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

Here we keep track of the experiments performed on the VANANZ library and the parsing process.

```{r}
library(tidyverse)
```

# List of experiments performed so far

This list is based on raw data files

```{r}
f <- list.files("Raw_data", full.names = T, recursive = T)
f
```

From the list extract files nested in the file structure `plateXX/expXXX/PI_kinetics` or `plateXX/expXXX/Growth_curves`

```{r}
f_data <- str_split_fixed(f, "/", n =5) %>%
  as.data.frame() 
colnames(f_data) <- c("dir", "plate", "experiment", "dataset", "file")

f_data <- f_data %>%
  filter(str_detect(plate, "plate") & dataset %in% c("Growth_curves", "PI_kinetics")) %>%
  mutate(experiment = str_remove(experiment, "_")) %>%
  unite(new_f, plate, experiment, remove = F) %>%
  select(-dir)
```

# Rename folder as plate-experiment to avoid duplicates

```{r}
dir.create("Data_parsing/parsed_experiments/foo")
file.rename("Data_parsing/parsed_experiments/foo",
            "Data_parsing/parsed_experiments/foo2")
file.remove("Data_parsing/parsed_experiments/foo2")


dir <- "Data_parsing/parsed_experiments/"

for (i in list.dirs(dir, full.names = F)) {
  new_f <- str_c(dir,
                 f_data %>%
                   filter(experiment == i) %>%
                   .$new_f %>%
                   unique())
  
  file.rename(str_c(dir, i), new_f)
}
```

