---
title: 'Parse results: plate 2 / exp190921'
author: "Stefano Giulieri"
date: "06/04/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse PI data

```{r}
PI_data <- parse_kinetics(file = "Raw_data/plate2/exp_190921/PI_kinetics/190921 HeLa real time cell death assay n4 using 20000 cells .xlsx",
                          exp = "exp190921",
                          duration = c(20,48),
                          n_skip = 13,
                          cell_number = 2e4,
                          wavelength = c(493,535),
                          plate = 2,
                          plot_data = T,
                          annotate = "minimal")
write_csv(PI_data,
          "Data_parsing/parsed_experiments/exp190921/PI_data_plate2_exp190921.csv")
```


# Parse growth data

No growth curves available for this experiment

