---
title: "Count replicates and datapoints"
author: "R Guerillot"
date: "06/03/2023"
output: html_document
---

```{r setup, include=T, message=FALSE}
library(tidyverse)
library(here)
library(patchwork)
setwd(paste0(here(), "/eLife_revision"))
getwd()
```

# Source all function

```{r message=FALSE}
rm(list = ls())
source("../0-Functions/all_functions.R")
```

# Import all VANANZ PI and growth curve data (plate 1-6 + P1-2, M1- GP1-7)

```{r}
raw_PI.df <- list.files(path="../3-Data_parsing/parsed_experiments/", pattern="PI", full.names=TRUE, recursive=T) %>% 
  map_df(~read_csv(., col_types = cols(well_row = col_factor(),
                                      well_col = col_factor(),
                                      f_signal = col_integer(),
                                      well = col_factor(),
                                      experiment = col_factor(),
                                      cell_number = col_factor(),
                                      plate = col_factor(),
                                      well_id = col_factor(),
                                      timepoint = col_integer(),
                                      sample_id = col_factor(),
                                      replicate = col_factor(),
                                      strain_group = col_factor()))) %>%
  filter(cell_number == 40000) %>%                        # Keep only data with 40000 HeLa cells
  mutate(experiment_id = str_c(experiment, "_", plate))   # Create a experiment variable that is unique
                                                          # -> two plate were done the same day => same exp.)

```

# Keep only clinical strains

```{r}
str_id <- readRDS("../5-Data_processing/processed_data/clinical_strains/PI_kinetics/PI_kinetics.Rds") %>%
  mutate(sample_id = as.character(sample_id)) %>%
  filter(grepl("BPH", sample_id)) %>%
  .$sample_id %>%
  unique()

raw_PI_clinical_str.df <- raw_PI.df %>%
  filter(sample_id %in% str_id)
```

# Import list of the 56 clinical isolats from the 28 pairs
```{r}
pairs_iso1 <- readRDS("../8-eLife_revision/Genetic_pairs/processed_data/PI_pairs_data/pairs_description_dataframe.Rda") %>%
  filter(PI_pair == T) %>%
  distinct(iso1) %>%
  .$iso1

pairs_iso2 <- readRDS("../8-eLife_revision/Genetic_pairs/processed_data/PI_pairs_data/pairs_description_dataframe.Rda") %>%
  filter(PI_pair == T) %>%
  distinct(iso2) %>%
  .$iso2

pairs_iso <- c(pairs_iso1, pairs_iso2) %>% unique()

```

# Count replicates all
```{r}
print(paste("Total number of PI plates:", 
            raw_PI_clinical_str.df %>% select(experiment_id) %>% distinct() %>% nrow()))


nb_replicate_per_strain.df <- raw_PI_clinical_str.df %>% select(sample_id, well_id) %>% distinct() %>%
  count(sample_id ,name = "number of strain replicate") %>% print()

nb_plate_replicate_plate_per_strain.df <- raw_PI_clinical_str.df %>% select(sample_id, experiment_id) %>% distinct() %>%
  count(sample_id ,name = "number of plate replicate") %>% print()

```


# Count replicates 56 strains from 28 pairs
```{r}
raw_PI_pairs_str.df <- raw_PI.df %>%
  filter(sample_id %in% pairs_iso)

print(paste("Total number of PI plates:", 
            raw_PI_pairs_str.df %>% select(experiment_id) %>% distinct() %>% nrow()))


nb_replicate_per_strain.df <- raw_PI_pairs_str.df %>% select(sample_id, well_id) %>% distinct() %>%
  count(sample_id ,name = "number of strain replicate") %>% print()

nb_plate_replicate_plate_per_strain.df <- raw_PI_pairs_str.df %>% select(sample_id, experiment_id) %>% distinct() %>%
  count(sample_id ,name = "number of plate replicate") %>% print()

```

# Count number of strains per plate

```{r}
t <- raw_PI.df %>%
  distinct(well_id, .keep_all = T) %>%
  group_by(experiment_id) %>%
  count(sample_id) %>% 
  count(sample_id)
```
