---
title: 'Parse results: plate M2 / exp200313'
author: "Stefano Giulieri"
date: "02/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse data

```{r}
# parameters
PI_data <- parse_kinetics(file = "Raw_data/plateM2/exp200313/PI_kinetics/200313 Plate M2 n1 HeLa 40000 cell death assay 24h.xlsx",
                          exp = "exp200313",
                          n_cycles = 222,
                          plate = "M2") %>%
  annotate_wells(well_info = "plate_info/well_info_plates_M1_M2.csv")
# save PI data
PI_data %>%
  write_csv("Data_parsing/parsed_experiments/exp200313/PI_data_plateM2_exp200313.csv")
```

# Parse growth data

```{r}
growth_data <- parse_growth(file = "Raw_data/plateM2/exp200313/Growth_curves/200315 Plate M2 Vananz n2 ON growth.xlsx",
                            duration = c(20,20),
                            interval = 10,
                            exp = "exp200313",
                            plate = "M2",
                            normalised = T,
                            annotate = "none"
) %>%
  annotate_wells(well_info = "plate_info/well_info_plates_M1_M2.csv")


# save growth data
growth_data %>%
  write_csv("Data_parsing/parsed_experiments/exp200313/growth_data_plateM2_exp200313.csv")
```