---
title: 'Parse results: plate 4 / exp191120'
author: "Stefano Giulieri"
date: "04/03/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
msg <- stringr::str_c("My directory is ", here::here())
print(msg)
```

```{r}
library(tidyverse)
library(magrittr)
rm(list = ls())
source("Functions/all_functions.R")
```

# Parse PI data

```{r}
PI_data <- parse_kinetics(file = "Raw_data/plate4/exp_191120/PI_kinetics/Vananz plate 4 191120 real time cell death n1.xlsx",
                          exp = "exp191120",
                          n_cycles = 225,
                          plate = 4,
                          annotate = "minimal")
# save PI data
write_csv(PI_data,
          "Data_parsing/parsed_experiments/exp191120/PI_data_plate4_exp191120.csv")
```


# Parse growth data

```{r}
growth_data <- parse_growth(file = "Raw_data/plate4/exp_191120/Growth_curves/191117 plate 4 ON growth n1.xlsx",
                            n_skip = 14,
                            duration = c(19,40),
                            interval = 10,
                            exp = "exp191120",
                            normalised = FALSE,
                            multiple_tranformations = c(3,1),
                            well_cols = "separated",
                            plate = 4,
                            annotate = "minimal"
)
# save growth data
growth_data %>%
  write_csv("Data_parsing/parsed_experiments/exp191120/growth_data_plate4_exp191120.csv")
```